### ISSUE TITLE
output format doesn't match migrate specifications

### ISSUE THREAD

**Issue by tommydevitt** [jinyung/loci2migrate#2]
After looking at the output, it doesn't appear that the formatting is correct for Migrate according to the manual for v4. My output using the script (shown only for the first 2 loci for the first two populations) is pasted below. It's missing the population names, and the number of characters for each locus is only printed for the first population. Subsequent populations list the number of individuals per locus, but not the number of characters.

14 586 
# These loci were not found in all populations and hence removed:
# 13217 20033 25632 4396 4696 
247 252 
9 9 
Indiv_0001 	ATGTGCATTTTTACATGTGTCTGTGAACTTGCATTACAGGGGTGCTGGGGTAGGTGTTGCTGTGCTTCGTGCTAGACGGTGTGTGAGGATTGGCAAGGTGTGGTGATGCATCTGGTnnnnCTCATTGCTCAAGGGGGGGTGTTTGTGAATTACCCAGCAGTATGCTGCGTGGTGGTACGCATTGCTCCATTGCTCTCAGGATGTGTACATCATGTGCTGATCCTGGGAGCTTTGCATACACCTG-CA 
Indiv_0002  ATGTGCATTTTTACATGTGTCTGTGAACTTGCATTACAGGGGTGCTGGGGTAGGTGTTGCTGTGCTTCGTGCTAGACGGTGTGTGAGGATTGGCAAGGTGTGGTGATGCATCTGGTnnnnCTCATTGCTCAAGGGGGGGTGTTTGTGAATTACCCAGCAGTATGCTGCGTGGTGGTACGCATTGCTCCATTGCTCTCAGGATGTGTACATCATGTGCTGATCCTGGGAGCTTTGCATACACCTG-CA 
Indiv_0003 	ATGTGCATTTTTACATGTGTCTGTGAACTTGCATTACAGGGGTGCTGGGGTAGGTGTTGCTGTGCTTCGTGCTAGACGGTGTGTGAGGATTGGCAAGGTGTGGTGATGCATCTGGTnnnnCTCATTGCTCAAGGGGGGGTGTTTGTGAATTACCCAGCAGTATGCTGCGTGGTGGTACGCATTGCTCCATTGCTCTCAGGATGTGTACATCATGTGCTGATCCTGGGAGCTTTGCATACACCTGCCA 
Indiv_0004 	ATGTGCATTTTTACATGTGTCTGTGAACTTGCATTACAGGGGTGCTGGGGTAGGTGTTGCTGTGCTTCGTGCTAGACGGTGTGTGAGGATTGGCAAGGTGTGGTGATGCATCTGGTnnnnCTCATTGCTCAAGGGGGGGTGTTTGTGAATTACCCAGCAGTATGCTGCGTGGTGGTACGCATTGCTCCATTGCTCTCAGGATGTGTACATCATGTGCTGATCCTGGGAGCTTTGCATACACCTG-CA 
Indiv_0005 	ATGTGCATTTTTACATGTGTCTGTGAACTTGCATTACAGGGGTGCTGGGGTAGGTGTTGCTGTGCTTCGTGCTAGACGGTGTGTGAGGATTGGCAAGGTGTGGTGATGCATCTGGTnnnnCTCATTGCTCAAGGGGGGGTGTTTGTGAATTACCCAGCAGTATGCTGCGTGGTGGTACGCATTGCTCCATTGCTCTCAGGATGTGTACATCATGTGCTGATCCTGGGAGCTTTGCATACACCTG-CA 
Indiv_0006 	ATGTGCATTTTTACATGTGTCTGTGAACTTGCATTACAGGGGTGCTGGGGTAGGTGTTGCTGTGCTTCGTGCTAGACGGTGTGTGAGGATTGGCAAGGTGTGGTGATGCATCTGGTnnnnCTCATTGCTCAAGGGGGGGTGTTTGTGAATTACCCAGCAGTATGCTGCGTGGTGGTACGCATTGCTCCATTGCTCTCAGGATGTGTACATCATGTGCTGATCCTGGGAGCTTTGCATACACCTG-CA 
Indiv_0007 	ATGTGCATTTTTACATGTGTCTGTGAACTTGCATTACAGGGGTGCTGGGGTAGGTGTTGCTGTGCTTCGTGCTAGACGGTGTGTGAGGATTGGCAAGGTGTGGTGATGCATCTGGTnnnnCTCATTGCTCAAGGGGGGGTGTTTGTGAATTACCCAGCAGTATGCTGCGTGGTGGTACGCATTGCTCCATTGCTCTCAGGATGTGTACATCATGTGCTGATCCTGGGAGCTTTGCATACACCTG-CA 
Indiv_0008 	ATGTGCATTTTTACATGTGTCTGTGAACTTGCATTACAGGGGTGCTGGGGTAGGTGTTGCTGTGCTTCGTGCTAGACGGTGTGTGAGGATTGGCAAGGTGTGGTGATGCATCTGGTnnnnCTCATTGCTCAAGGGGGGGTGTTTGTGAATTACCCAGCAGTATGCTGCGTGGTGGTACGCATTGCTCCATTGCTCTCAGGATGTGTACATCATGTGCTGATCCTGGGAGCTTTGCATACACCTG-CA 
Indiv_0009 	ATGTGCATTTTTACATGTGTCTGTGAACTTGCATTACAGGGGTGCTGGGGTAGGTGTTGCTGTGCTTCGTGCTAGACGGTGTGTGAGGATTGGCAAGGTGTGGTGATGCATCTGGTnnnnCTCATTGCTCAAGGGGGGGTGTTTGTGAATTACCCAGCAGTATGCTGCGTGGTGGTACGCATTGCTCCATTGCTCTCAGGATGTGTACATCATGTGCTGATCCTGGGAGCTTTGCATACACCTG-CA 
# 10186 
Indiv_0001	 TAGAACTCTCCTCCSTGAGATGACTTGTTTTTCTCAGTGACCAGCTTGTTTTGTGTTTTG-TATTGAACCTCTAAGAAAAGARTG-AAAARTCATATGGTAGTCTGAAAAATACATTTnnnnCCTAGCAGCAGCTGAAGATTTGATTT-CCCCATAGTTAGGGTTGG-CCATGCAGGGTTTGAAA-TTAGCAGTCGTCCCGGAGCMAGAGGCTCCTTGTTTTTAATTTGGGCTCCC-TACTGTGCACCTGCA 
Indiv_0002	 TAGAACTCTCCTCCGTGAGATGACTTGTTTTTCTCAGTGACCAGCTTGTTTTGTGTTTTG-TATTGAACCTCTAAGAAAAGAGTG-AAAAGTCATATGGTAGTCTGAAAAATACATTTnnnnCCTAGCAGCAGCTGAAGATTTGATTT-CCCCATAGTTAGGGTTGG-CCATGCAGGGTTTGAAA-TTAGCAGTCGTCCCGGAGCAAGAGGCTCCTTGTTTTTAATTTGGGCTCCC-TACTGTGCACCTGCA 
Indiv_0003	 TAGAACTCTCCTCCGTGAGATGACTTGTTTTTCTCAGTGACCAGCTTGTTTTGTGTTTTG-TATTGAACCTCTAAGAAAAGAGTG-AAAAGTCATATGGTAGTCTGAAAAATACATTTnnnnCCTAGCAGCAGCTGAAGATTTGATTT-CCCCATAGTTAGGGTTGG-CCATGCAGGGTTTGAAA-TTAGCAGTCGTCCCGGAGCAAGAGGCTCCTTGTTTTTAATTTGGGCTCCC-TACTGTGCACCTGCA 
Indiv_0004	 TAGAACTCTCCTCCGTGAGATGACTTGTTTTTCTCAGTGACCAGCTTGTTTTGTGTTTTG-TATTGAACCTCTAAGAAAAGAGTG-AAAAGTCATATGGTAGTCTGAAAAATACATTTnnnnCCTAGCAGCAGCTGAAGATTTGATTT-CCCCATAGTTAGGGTTGG-CCATGCAGGGTTTGAAA-TTAGCAGTCGTCCCGGAGCAAGAGGCTCCTTGTTTTTAATTTGGGCTCCC-TACTGTGCACCTGCA 
Indiv_0005	 TAGAACTCTCCTCCSTGAGATGACTTGTTTTTCTCAGTGACCAGCTTGTTTTGTGTTTTG-TATTGAACCTCTAAGAAAAGARTG-AAAARTCATATGGTAGTCTGAAAAATACATTTnnnnCCTAGCAGCAGCTGAAGATTTGATTT-CCCCATAGTTAGGGTTGG-CCATGCAGGGTTTGAAA-TTAGCAGTCGTCCCGGAGCMAGAGGCTCCTTGTTTTTAATTTGGGCTCCC-TACTGTGCACCTGCA 
Indiv_0006	 TAGAACTCTCCTCCGTGAGATGACTTGTTTTTCTCAGTGACCAGCTTGTTTTGTGTTTTG-TATTGAACCTCTAAGAAAAGAGTG-AAAAGTCATATGGTAGTCTGAAAAATACATTTnnnnCCTAGCAGCAGCTGAAGATTTGATTT-CCCCATAGTTAGGGTTGG-CCATGCAGGGTTTGAAA-TTAGCAGTCGTCCCGGAGCAAGAGGCTCCTTGTTTTTAATTTGGGCTCCC-TACTGTGCACCTGCA 
Indiv_0007	 TAGAACTCTCCTCCGTGAGATGACTTGTTTTTCTCAGTGACCAGCTTGTTTTGTGTTTTG-TATTGAACCTCTAAGAAAAGAGTG-AAAAGTCATATGGTAGTCTGAAAAATACATTTnnnnCCTAGCAGCAGCTGAAGATTTGATTT-CCCCATAGTTAGGGTTGG-CCATGCAGGGTTTGAAA-TTAGCAGTCGTCCCGGAGCAAGAGGCTCCTTGTTTTTAATTTGGGCTCCC-TACTGTGCACCTGCA 
Indiv_0008	 TAGAACTCTCCTCCGTGAGATGACTTGTTTTTCTCAGTGACCAGCTTGTTTTGTGTTTTG-TATTGAACCTCTAAGAAAAGAGTG-AAAAGTCATATGGTAGTCTGAAAAATACATTTnnnnCCTAGCAGCAGCTGAAGATTTGATTT-CCCCATAGTTAGGGTTGG-CCATGCAGGGTTTGAAA-TTAGCAGTCGTCCCGGAGCAAGAGGCTCCTTGTTTTTAATTTGGGCTCCC-TACTGTGCACCTGCA 
Indiv_0009	 TAGAACTCTCCTCCSTGAGATGACTTGTTTTTCTCAGTGACCAGCTTGTTTTGTGTTTTG-TATTGAACCTCTAAGAAAAGARTG-AAAARTCATATGGTAGTCTGAAAAATACATTTnnnnCCTAGCAGCAGCTGAAGATTTGATTT-CCCCATAGTTAGGGTTGG-CCATGCAGGGTTTGAAA-TTAGCAGTCGTCCCGGAGCMAGAGGCTCCTTGTTTTTAATTTGGGCTCCC-TACTGTGCACCTGCA 
# 10190 
....

**Comment by jinyung** [comment]
Thanks for the feedback. I personally is not a user of migrate nor working on RADseq so it will help if you can tell me more to help me understand the issue. My understanding is: 
1. this script probably follows the old format, but is not compatible with new format of migrate?
2. new format prints population name, where should this information be? can you indicate in the sample you provided?
3. yes sequence length is printed only in the first population. so the same thing should be repeated for every population?

Anything I missed?

**Comment by tommydevitt** [comment]
> Thanks for the feedback. I personally is not a user of migrate nor working on RADseq so it will help if you can tell me more to help me understand the issue. My understanding is:
> 
> 1. this script probably follows the old format, but is not compatible with new format of migrate?

I'm not sure of that; I'm using Migrate version 4.

> 2. new format prints population name, where should this information be? can you indicate in the sample you provided?

The population name should go at the end of the line containing the number of individuals for a given locus/population block. In the example above,

9 9 Population1

> 3. yes sequence length is printed only in the first population. so the same thing should be repeated for every population?

Sorry, I should have said the sequence length is printed only for the first locus. The sequence lengths may vary by locus, and so each locus should have the sequence length line.

> Anything I missed?

I don't think so, but it may be easier to look here in case I wasn't clear: https://peterbeerli.com/migrate-html5/download_version4/migratedoc4.x.pdf

Thanks!

**Comment by jinyung** [comment]
According to the pdf link you gave me, the script does give output that looks like the one shown on p.18 (I assume this is what you need?). 

Sorry I didn't check clearly on your question at first, the script already print population name at the end of the line stating number of individuals of each locus. And already print sequence lengths of each locus, once at the top of first population, assuming each locus has the same length.

Sorry I cannot reproduce your problem. If you don't mind, send me the files to test.

**Comment by tommydevitt** [comment]
Thanks for taking a look. The input files are too large to send; do you use DropBox? Or Box? Google Drive?

Tom

**Comment by jinyung** [comment]
script improved to match migrate specification in commit  a4b1ecaeb5fac9a769289657117106b2c33531f3
